/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify-email` | `/verify-email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify-phone` | `/verify-phone`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/browse` | `/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-learning` | `/my-learning`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications-tab` | `/notifications-tab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/course/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/learn/[courseId]`, params: Router.UnknownInputParams & { courseId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verify-email` | `/verify-email`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verify-phone` | `/verify-phone`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/browse` | `/browse`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-learning` | `/my-learning`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notifications-tab` | `/notifications-tab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/course/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/learn/[courseId]`, params: Router.UnknownOutputParams & { courseId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot-password${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verify-email${`?${string}` | `#${string}` | ''}` | `/verify-email${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verify-phone${`?${string}` | `#${string}` | ''}` | `/verify-phone${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/browse${`?${string}` | `#${string}` | ''}` | `/browse${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-learning${`?${string}` | `#${string}` | ''}` | `/my-learning${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notifications-tab${`?${string}` | `#${string}` | ''}` | `/notifications-tab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify-email` | `/verify-email`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify-phone` | `/verify-phone`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/browse` | `/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-learning` | `/my-learning`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications-tab` | `/notifications-tab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/course/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/learn/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/course/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/learn/[courseId]`, params: Router.UnknownInputParams & { courseId: string | number; } };
    }
  }
}
